name: finsight
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  csv: ^6.0.0
  path_provider: ^2.1.5
  http: ^1.2.2  
  open_file: ^3.5.9
  intl: ^0.19.0
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^8.0.0
  plaid_flutter: ^2.0.0
  google_sign_in: ^6.2.2
  collection: ^1.18.0
  pdf: ^3.11.1
  printing: ^5.13.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/monthly_spending_categories.csv
    - assets/data/account_balances.csv
    - assets/data/credit_score.csv
    - assets/data/monthly_cashflow.csv
    - assets/data/transactions.csv
    - assets/images/logo.png
    - assets/images/logo_cropped.png
    - assets/images/google_logo.png
    - assets/fonts/Roboto-Regular.ttf