name: fbla_coding_programming_app
description: "A new Flutter project for FBLA."

# Prevents accidental publishing to pub.dev
publish_to: 'none' 

# Version information
version: 1.0.0+1

# Min Dart SDK version required for the project
environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.0.0
  csv: ^5.0.0
  path_provider: ^2.0.9

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true
