name: fbla_coding_programming_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  csv: ^6.0.0
  path_provider: ^2.0.11
  http: ^1.2.2
  open_file: ^3.2.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/monthly_spending_categories.csv
    - assets/data/account_balances.csv
    - assets/data/credit_score.csv
    - assets/data/monthly_cashflow.csv
    - assets/data/transactions.csv
