name: fbla_coding_programming_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  csv: ^6.0.0
  path_provider: ^2.0.11
  http: ^1.2.2  
  open_file: ^3.2.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  flutter_secure_storage: ^8.0.0
  plaid_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/monthly_spending_categories.csv
    - assets/data/account_balances.csv
    - assets/data/credit_score.csv
    - assets/data/monthly_cashflow.csv
    - assets/data/transactions.csv